#!/usr/bin/env python3
"""
Environment Setup Script for F1 Prediction System
Helps users configure API keys and environment variables
"""

import os
import sys
from pathlib import Path

def setup_environment():
    """Interactive setup for environment variables"""
    print("🚀 F1 Prediction System Environment Setup")
    print("=" * 50)
    
    # Check if .env file exists
    env_file = Path(".env")
    env_vars = {}
    
    if env_file.exists():
        print("📁 Found existing .env file")
        with open(env_file, 'r') as f:
            for line in f:
                if '=' in line and not line.startswith('#'):
                    key, value = line.strip().split('=', 1)
                    env_vars[key] = value
    
    print("\n🔑 API Configuration Options:")
    print("1. Jolpica F1 API (Recommended - Live 2024/2025 data)")
    print("   - Free tier available")
    print("   - Current season data")
    print("   - Qualifying results, standings, live sessions")
    print("   - Sign up at: https://jolpica.com")
    
    print("\n2. Ergast API (Fallback - Historical data only)")
    print("   - Completely free")
    print("   - No authentication required")
    print("   - Data ends at 2023 season")
    print("   - URL: http://ergast.com/api/f1")
    
    print("\n3. Use fallback data only")
    print("   - No API calls")
    print("   - Uses hardcoded 2025 driver list")
    print("   - Good for testing/development")
    
    choice = input("\n🎯 Choose your setup (1/2/3): ").strip()
    
    if choice == "1":
        setup_jolpica_api(env_vars)
    elif choice == "2":
        setup_ergast_api(env_vars)
    elif choice == "3":
        setup_fallback_only(env_vars)
    else:
        print("❌ Invalid choice. Using fallback setup.")
        setup_fallback_only(env_vars)
    
    # Write .env file
    write_env_file(env_vars)
    
    print("\n✅ Environment setup complete!")
    print("📝 Next steps:")
    print("   1. Restart your backend server")
    print("   2. Run: python test_hybrid_predictions.py")
    print("   3. Test API endpoints")

def setup_jolpica_api(env_vars):
    """Setup Jolpica API configuration"""
    print("\n🔑 Jolpica F1 API Setup")
    print("-" * 30)
    
    print("📋 To get your API key:")
    print("   1. Visit: https://jolpica.com")
    print("   2. Sign up for a free account")
    print("   3. Navigate to API section")
    print("   4. Copy your API key")
    
    api_key = input("\n🔑 Enter your Jolpica API key: ").strip()
    
    if api_key:
        env_vars["JOLPICA_API_KEY"] = api_key
        print("✅ Jolpica API key configured")
    else:
        print("⚠️ No API key provided - will use fallback")

def setup_ergast_api(env_vars):
    """Setup Ergast API configuration"""
    print("\n🔑 Ergast API Setup")
    print("-" * 30)
    
    print("✅ Ergast API requires no configuration!")
    print("📊 Will use historical data (up to 2023 season)")
    
    # Clear any existing Jolpica key
    if "JOLPICA_API_KEY" in env_vars:
        del env_vars["JOLPICA_API_KEY"]

def setup_fallback_only(env_vars):
    """Setup fallback-only configuration"""
    print("\n🔑 Fallback Setup")
    print("-" * 30)
    
    print("✅ Using fallback data only")
    print("📊 Will use hardcoded 2025 driver list")
    
    # Clear any existing API keys
    if "JOLPICA_API_KEY" in env_vars:
        del env_vars["JOLPICA_API_KEY"]

def write_env_file(env_vars):
    """Write environment variables to .env file"""
    env_file = Path(".env")
    
    with open(env_file, 'w') as f:
        f.write("# F1 Prediction System Environment Variables\n")
        f.write("# Generated by setup_env.py\n\n")
        
        for key, value in env_vars.items():
            f.write(f"{key}={value}\n")
    
    print(f"📝 Environment variables written to {env_file}")

def test_environment():
    """Test the current environment configuration"""
    print("\n🧪 Testing Environment Configuration...")
    
    # Load environment variables
    env_file = Path(".env")
    if env_file.exists():
        with open(env_file, 'r') as f:
            for line in f:
                if '=' in line and not line.startswith('#'):
                    key, value = line.strip().split('=', 1)
                    os.environ[key] = value
    
    # Test API availability
    jolpica_key = os.getenv("JOLPICA_API_KEY")
    
    if jolpica_key:
        print("✅ Jolpica API key found")
        print("📊 Will use live 2024/2025 data")
    else:
        print("⚠️ No Jolpica API key found")
        print("📊 Will use Ergast API (historical data) or fallback")
    
    print("✅ Environment test complete")

if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "test":
        test_environment()
    else:
        setup_environment()

